# Generated by Django 5.0.3 on 2024-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name=' Student name')),
                ('age', models.IntegerField(verbose_name='Student age')),
                ('mark_1', models.IntegerField(verbose_name='mathematical analysis')),
                ('mark_2', models.IntegerField(verbose_name='physics')),
                ('mark_3', models.IntegerField(verbose_name='geometry')),
                ('mark_4', models.IntegerField(verbose_name='artificial intelligence')),
                ('mark_5', models.IntegerField(verbose_name='philosophy')),
                ('mark_6', models.IntegerField(verbose_name='algebra')),
                ('mark_7', models.IntegerField(verbose_name='history')),
            ],
            options={
                'verbose_name': 'Students list',
                'db_table': 'student',
            },
        ),
    ]
