# Generated by Django 5.0.3 on 2024-03-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id',), 'verbose_name': 'Students list'},
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='Rasm joylanmagan', upload_to='students', verbose_name='Student image'),
        ),
    ]
